### ISSUE TITLE
v2.0 branch has removed project.pbxproj

### ISSUE THREAD

**Issue by pix0r** [gdavis/FGallery-iPhone#55]
I was just trying to demo the v2.0 branch and found that the project.pbxproj file was removed in commit 73447ae.  Xcode can't open the project unless this file is present.

**Comment by gdavis** [comment]
The version 2.0 is not yet ready for release or testing. The previous project file has been removed and replaced with GDIImageGallery.xcodeproj which compiles the static library. You’ll also notice, the project is going to be renamed to GDIImageGallery. The demo workspace project is where you can poke around to test it, but its far from complete since I’m rewriting much of it.
